#!/bin/bash

#
# 2022-02-25 Toggle xautolock + xlock (screensaver only) and DPMS by Tom Wizetek
#

dpms_state=$(xset q | awk '/DPMS is/ {print $3}')

case ${dpms_state} in

Disabled)
  xautolock -enable
  xset +dpms
  notify-send "Display saver ON" "Enabled screensaver and DPMS"
;;

Enabled)
  xautolock -disable
  xset -dpms
  notify-send "Display Saver OFF" "Disabled screensaver and DPMS"
;;

esac

##
