#!/usr/bin/env bash

# Tom Wizetek <tom@wizetek.com> 2021-05-24, 2023-02-07, 2024-04-07
#
# SoX args:
# [q]uiet
# [V]erbosity level
# [G]uard against clipping via gain effect
#   G = gain -h gain -r
#     -h = headroom
#     -r = reclaim
# [n]ull input/output file (for synth)
#
# synth:
# by default incorporates 'gain -h'
# vol headroom to avoid clipping: >3dB
# treble/bass <gain> useful values: -20<0<+20
# tremolo <speed> [depth]
# fade [type] <length>
#   t = triangular/linear type
#
# example:
# play -q -V0 -G -n synth pinknoise vol -3dB treble -10 bass -3 fade t 2

SYNTH1="whitenoise vol -90dB tremolo .3 90"
SYNTH2="pinknoise vol -3dB treble -10 bass -3"
SYNTH3="brownnoise vol -90dB"
ARGS="fade t 2"
#SOX_ARGS="--no-show-progress -V0 --guard --null"
SOX_ARGS="-q -V0 -G -n"
SAVED_PID="/tmp/$(basename ${0})-${UID}"

addPID() {
  echo ${!} >> ${SAVED_PID}
}

clearPID() {
  echo -n "" > ${SAVED_PID}
}

playNoise() {
  play ${SOX_ARGS} synth ${SYNTH1} ${ARGS} &
  addPID

  play ${SOX_ARGS} synth ${SYNTH2} ${ARGS} &
  addPID

  play ${SOX_ARGS} synth ${SYNTH3} ${ARGS} &
  addPID
}

killNoise() {
  [[ ! -f ${SAVED_PID} ]] && touch ${SAVED_PID}

  while read READ_PID; do
    kill ${KILL_SIG} ${READ_PID}
  done < ${SAVED_PID}
}

toggleNoise() {
  if [[ -s ${SAVED_PID} ]]; then
    killNoise
    clearPID
    echo "$(basename ${0}) off"
  else
    playNoise
    echo "$(basename ${0}) on"
  fi
}

case ${1} in

-h|*help)
  cat << HELP_TEXT

$(basename ${0})
                toggle noise on/off
 -f, --force    force noise
 -k, --kill     kill noise

HELP_TEXT
;;

-f|*force)
  killNoise
  clearPID
  playNoise
;;

-k|*kill)
  KILL_SIG="-9"
  killNoise
  clearPID
;;

*)
  KILL_SIG=""
  toggleNoise
;;

esac

##
